/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ElAvatar: typeof import('element-plus/es/components/avatar/index')['ElAvatar']
    ElButton: typeof import('element-plus/es/components/button/index')['ElButton']
    ElForm: typeof import('element-plus/es/components/form/index')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index')['ElFormItem']
    ElHeader: typeof import('element-plus/es/components/container/index')['ElHeader']
    ElIcon: typeof import('element-plus/es/components/icon/index')['ElIcon']
    ElInput: typeof import('element-plus/es/components/input/index')['ElInput']
    ElMain: typeof import('element-plus/es/components/container/index')['ElMain']
    ElTag: typeof import('element-plus/es/components/tag/index')['ElTag']
    IEpChatDotRound: typeof import('~icons/ep/chat-dot-round')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpPromotion: typeof import('~icons/ep/promotion')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
